### ISSUE TITLE
Breaks on puppet-lint 2.4.0

### ISSUE THREAD

**Issue by baurmatt** [rodjek/puppet-lint-trailing_newline-check#4]
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.4.0
ruby version: 2.5.3-p105
platform: x86_64-darwin18
file path: site/exim/manifests//params.pp
file contents:
```
# Class: exim::params
#
class exim::params () {

  case $::operatingsystem {
    'gentoo': {
      $package = 'mail-mta/exim'
      $service = 'exim'
      $aliases_target = '/etc/mail/aliases'
      $cfgdir = '/etc/exim'
      $cfgfile = "${cfgdir}/exim.conf"
      $logfile = '/var/log/exim/exim_main.log'
      $trusted_users_apache = ['apache']
      $trusted_users_nginx = ['nginx']
      $pid = undef
      $add_environment = undef
      $keep_environment = false
      $os_config = {}
    }
    'ubuntu', 'debian': {
      $package = 'exim4'
      $service = 'exim4'
      $aliases_target = '/etc/aliases'
      $cfgdir = '/etc/exim4'
      $cfgfile = "${cfgdir}/exim4.conf"
      $logfile = '/var/log/exim4/mainlog'
      $trusted_users_apache = ['www-data']
      $trusted_users_nginx = ['www-data']
      $pid = '/var/run/exim4/exim.pid'
      $add_environment = undef
      $keep_environment = '' # lint:ignore:empty_string_assignment
      $os_config = {
        global_options   => {
          keep_environment => '',
        },
      }
    }
    'centos': {
      $package = 'exim'
      $service = 'exim'
      $aliases_target = '/etc/aliases'
      $cfgdir = '/etc/exim'
      $cfgfile = "${cfgdir}/exim.conf"
      $logfile = '/var/log/exim/main.log'
      $trusted_users_apache = ['apache']
      $trusted_users_nginx = ['nginx']
      $pid = undef
      $add_environment = undef
      $keep_environment = '' # lint:ignore:empty_string_assignment
      $os_config = {
        global_options   => {
          keep_environment => '',
        },
      }
    }
    default: {
      fail("Unknown OS: ${::operatingsystem}")
    }
  }

  $common_config = {
    adminserver          => undef,
    maildomain           => '@',
    global_options       => {
      primary_hostname              => $::fqdn,
      'domainlist local_domains'    => '@',
      'domainlist relay_to_domains' => '',
      'hostlist relay_from_hosts'   => '127.0.0.1 : ::::1 : ',
      acl_smtp_rcpt                 => 'acl_check_rcpt',
      acl_smtp_data                 => 'acl_check_data',
      never_users                   => 'root',
      trusted_users                 => '',
      rfc1413_hosts                 => '*',
      rfc1413_query_timeout         => '0s', # This disables the ident callback
      ignore_bounce_errors_after    => '2d',
      timeout_frozen_after          => '7d',
    },
    acls                 => {
      check_rcpt => 'exim/exim_acl_check_rcpt.inc',
      check_data => 'exim/exim_acl_check_data.inc',
    },
    routers              => [
      {
        dnslookup => {
          driver              => 'dnslookup',
          domains             => '! +local_domains',
          transport           => 'remote_smtp',
          ignore_target_hosts => '0.0.0.0 : 127.0.0.0/8',
          no_more             => undef,
        },
      },
      {
        system_aliases => {
          driver         => 'redirect',
          allow_fail     => undef,
          allow_defer    => undef,
          data           => "\${lookup{\$local_part}lsearch{${aliases_target}}}",
          file_transport => 'address_file',
          pipe_transport => 'address_pipe',
        },
      },
    ],
    transports           => {
      remote_smtp    => {
        driver => 'smtp',
      },
    },
    retries              => [
      '* * F,2h,15m; G,16h,1h,1.5; F,4d,6h',
    ],
    rewrites             => [],
    authenticators       => {},
  }

  $default_config = deep_merge($common_config, $os_config)
}

```
error:
```
NoMethodError: undefined method `type' for nil:NilClass
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-trailing_newline-check-1.1.0/lib/puppet-lint/plugins/check_trailing_newline.rb:5:in `check'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/checks.rb:61:in `block in run'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/checks.rb:58:in `each'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/checks.rb:58:in `run'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint.rb:205:in `run'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/bin.rb:66:in `block in run'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/bin.rb:62:in `each'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/lib/puppet-lint/bin.rb:62:in `run'
/Users/mbaur/.rvm/gems/ruby-2.5.3/gems/puppet-lint-2.4.0/bin/puppet-lint:7:in `<top (required)>'
/Users/mbaur/.rvm/gems/ruby-2.5.3/bin/puppet-lint:23:in `load'
/Users/mbaur/.rvm/gems/ruby-2.5.3/bin/puppet-lint:23:in `<main>'
/Users/mbaur/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/Users/mbaur/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by baurmatt** [comment]
Magically fixed with 2.4.1 :)
